<a href="https://colab.research.google.com/github/Manisha1896/python/blob/main/ClassNotes_Data_Analytics_17July_21July23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [ ]:
import numpy as np # import numpy library

In [ ]:
a = [1,2,3,4,5]  # create a list

In [ ]:
type(a)

list

In [ ]:
b = np.array(a) # Transform list into array

In [ ]:
type(b) # Check the type of array

numpy.ndarray

In [ ]:
print(b)

[1 2 3 4 5]


In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
b.shape # Shape checks the number of dimension

(5,)

In [ ]:
type(b.shape)

tuple

In [ ]:
nested_list = [[1,2,5],[3,4,5]] # nested list

In [ ]:
two_d_array = np.array(nested_list) # transform nested list into array

In [ ]:
two_d_array

array([[1, 2, 5],
       [3, 4, 5]])

In [ ]:
two_d_array.dtype # check the datatype of elements which are inside array

dtype('int64')

In [ ]:
two_d_array.shape # overall shape of array

(2, 3)

In [ ]:
lst1 = [[1,2,5]]
two_d_array1 = np.array(lst1)
two_d_array1.shape # 2-d array with 1 row and 3 columns

(1, 3)

In [ ]:
two_d_array1

array([[1, 2, 5]])

In [ ]:
emp = [[1,'Amit',25000],[2,'Allen',35000]]
emp_array = np.array(emp)
type(emp_array)

numpy.ndarray

In [ ]:
emp_array

array([['1', 'Amit', '25000'],
       ['2', 'Allen', '35000']], dtype='<U21')

In [ ]:
emp_array.shape

(2, 3)

In [ ]:
a1 = [ [   [1,2,1,1],[3,4,1,1]  ] ]

In [ ]:
three_d_array = np.array(a1) # 3-d array example

In [ ]:
three_d_array

array([[[1, 2, 1, 1],
        [3, 4, 1, 1]]])

In [ ]:
three_d_array.shape

(1, 2, 4)

In [ ]:
lst1 = [1,2,3]
lst2 = [4,5,6]
lst1+lst2

[1, 2, 3, 4, 5, 6]

In [ ]:
result = []
for i in range(0,3):
  result.append(lst1[i]+lst2[i])
print(result)

[5, 7, 9]


In [ ]:
arr1 = np.array(lst1)
arr2 = np.array(lst2)
arr1+arr2

array([5, 7, 9])

Broadcasting

In [ ]:
lst1 = [1,2,3]
arr1 = np.array(lst1)

In [ ]:
lst1[0:2] = 100

TypeError: ignored

In [ ]:
arr1[0:2] = 100

In [ ]:
arr1

array([100, 100,   3])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
x = np.zeros((3,3))

In [ ]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

18-July-23 classnotes

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
from random import randint
randint(1,100)

82

In [ ]:
np.random.randint(1,100,10)

array([84, 68, 26, 27, 19, 63,  3, 79, 93, 71])

In [ ]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
import numpy as np

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = [[1,2,10],[3,4,11]]
arr1 = np.array(a)

In [ ]:
arr1

array([[ 1,  2, 10],
       [ 3,  4, 11]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr2 = np.arange(1,10)

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2.shape

(9,)

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.reshape(4,3)

ValueError: ignored

NaN vs None

In [ ]:
a = None
a1 = np.nan

In [ ]:
type(a)

NoneType

In [ ]:
type(a1)

float

In [ ]:
print(type(a1))

<class 'float'>


In [ ]:
a1

nan

Indexing

In [ ]:
arr2 = np.arange(1,10)

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2[0:3]

array([1, 2, 3])

In [ ]:
arr2[4:6]

array([5, 6])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
arr2d = np.zeros((10,10))

In [ ]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr2d[0] = 10

In [ ]:
arr2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
arr2d[1] = 20
arr2d[2] = 30
arr2d[3] = 40
arr2d[4] = 50

In [ ]:
arr2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.],
       [30., 30., 30., 30., 30., 30., 30., 30., 30., 30.],
       [40., 40., 40., 40., 40., 40., 40., 40., 40., 40.],
       [50., 50., 50., 50., 50., 50., 50., 50., 50., 50.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
arr2d[3,4]

40.0

In [ ]:
arr2d[[0,4]]

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [50., 50., 50., 50., 50., 50., 50., 50., 50., 50.]])

In [ ]:
arr2d[[0,4,1]]

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [50., 50., 50., 50., 50., 50., 50., 50., 50., 50.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.]])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
arr = np.arange(0,5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr+arr

array([0, 2, 4, 6, 8])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16])

In [ ]:
arr ** 3

array([ 0,  1,  8, 27, 64])

Numpy assessment: https://colab.research.google.com/drive/1Q7v6b0tofHiBGzqNSc2jfUficMdqdDZA?usp=sharing

Introduction to Pandas

# Series

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [ ]:
data={'maths':[98,99],'chemistry':[60,61]}

In [ ]:
type(data)

dict

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(data)

maths  chemistry
0     98         60
1     99         61

In [ ]:
emp = {'name':['Rohan','Pooja','Akash'] , 'eid':[1,2,3],'sal':[25000,35000,45000]}

In [ ]:
df = pd.DataFrame(emp)

In [ ]:
df

name  eid    sal
0  Rohan    1  25000
1  Pooja    2  35000
2  Akash    3  45000

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df['sal']

0    25000
1    35000
2    45000
Name: sal, dtype: int64

In [ ]:
type(df['eid'])

pandas.core.series.Series

In [ ]:
df[['eid','name']]

eid   name
0    1  Rohan
1    2  Pooja
2    3  Akash

In [ ]:
df

name  eid    sal
0  Rohan    1  25000
1  Pooja    2  35000
2  Akash    3  45000

In [ ]:
df['sal'] > 30000

0    False
1     True
2     True
Name: sal, dtype: bool

In [ ]:
df[ df['sal'] > 30000 ]

name  eid    sal
1  Pooja    2  35000
2  Akash    3  45000



1. We can automate the tasks
2. Data scalability is a challange
3. Distributed and parallel processing
4. Limitation in DF - temp storage



Series

In [ ]:
my_list = [10,20,30]

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
custom_index = ['a','b','c']
my_list = [10,20,30]
pd.Series(my_list,custom_index)

a    10
b    20
c    30
dtype: int64

In [ ]:
d = {'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
d = {'a':[10,11],'b':[20,21],'c':[30,31]}
pd.Series(d)

a    [10, 11]
b    [20, 21]
c    [30, 31]
dtype: object

In [ ]:
d = {'a':10,'a':20,'c':30}
d

{'a': 20, 'c': 30}

In [ ]:
pd.Series(d)

a    20
c    30
dtype: int64

In [ ]:
data={'maths':[98,99,82,91,78],'chemistry':[97,99,87,72,65],'physics':[97,82,98,68,55]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

In [ ]:
df['maths']

0    98
1    99
2    82
3    91
4    78
Name: maths, dtype: int64

In [ ]:
df[['maths','chemistry']]

maths  chemistry
0     98         97
1     99         99
2     82         87
3     91         72
4     78         65

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

**Create a new column:**

In [ ]:
df['total_marks'] = df['maths'] + df['chemistry'] + df['physics']

0    292
1    280
2    267
3    231
4    198
dtype: int64

In [ ]:
df

maths  chemistry  physics  total_marks
0     98         97       97          292
1     99         99       82          280
2     82         87       98          267
3     91         72       68          231
4     78         65       55          198

**Remove Column**

1.   axis = 0 means index/ row   and axis = 1 means column
2.   inplace = True means overwrite existing dataframe with changes



In [ ]:
df.drop('total_marks',axis=1,inplace=True)

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

In [ ]:
df.drop(4,axis=0)

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

In [ ]:
df['maths']  #select specific column

0    98
1    99
2    82
3    91
4    78
Name: maths, dtype: int64

In [ ]:
df[['maths','physics']]  #select more than one column column

maths  physics
0     98       97
1     99       82
2     82       98
3     91       68
4     78       55

In [ ]:
df.iloc[0] # index wise locate

maths        98
chemistry    97
physics      97
Name: 0, dtype: int64

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

In [ ]:
df.iloc[0:2]

maths  chemistry  physics
0     98         97       97
1     99         99       82

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

In [ ]:
df>90

maths  chemistry  physics
0   True       True     True
1   True       True    False
2  False      False     True
3   True      False    False
4  False      False    False

In [ ]:
df[df>90]

maths  chemistry  physics
0   98.0       97.0     97.0
1   99.0       99.0      NaN
2    NaN        NaN     98.0
3   91.0        NaN      NaN
4    NaN        NaN      NaN

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
x = 'Amit Smith Allen Kathy John'.split()

In [ ]:
x

['Amit', 'Smith', 'Allen', 'Kathy', 'John']

In [ ]:
df

maths  chemistry  physics
0     98         97       97
1     99         99       82
2     82         87       98
3     91         72       68
4     78         65       55

In [ ]:
df['names'] = x

In [ ]:
df

maths  chemistry  physics  names
0     98         97       97   Amit
1     99         99       82  Smith
2     82         87       98  Allen
3     91         72       68  Kathy
4     78         65       55   John

In [ ]:
df.set_index('names',inplace=True)

In [ ]:
df.loc['Smith']

maths        99
chemistry    99
physics      82
Name: Smith, dtype: int64

In [ ]:
df.iloc[1]

maths        99
chemistry    99
physics      82
Name: Smith, dtype: int64

20-July-23 classnotes **Pandas operations**

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.drop('A',axis=1)

B  C
0  5.0  1
1  NaN  2
2  NaN  3

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(axis=0) # remove / drop all those records which contain NaN value

A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1) # remove / drop all those columns which contain NaN value

C
0  1
1  2
2  3

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(thresh=1) # thresh means minimum number of non-Nan Values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(thresh=2) # thresh means minimum number of non-Nan Values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df.dropna(thresh=4) # thresh means minimum number of non-Nan Values

Empty DataFrame
Columns: [A, B, C]
Index: []

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.fillna(value='Test')

A     B  C
0   1.0   5.0  1
1   2.0  Test  2
2  Test  Test  3

In [ ]:
data = {'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df # display all columns and records

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df.head(2) # display first 2 records

col1  col2 col3
0     1   444  abc
1     2   555  def

In [ ]:
df.tail(2) # display last 2 records

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

### Info on Unique Values

In [ ]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df['col2'].unique()  #  Display unique values

array([444, 555, 666])

In [ ]:
df['col2'].nunique() #  Display count of unique  (number of unqiue)  values

3

In [ ]:
df['col1'].unique() #  Display unique values

array([1, 2, 3, 4])

In [ ]:
df['col1'].nunique() #  Display count of unique (number of unqiue) values

4

In [ ]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df['col2'].value_counts() #  Display unique values with individual value's count

444    2
555    1
666    1
Name: col2, dtype: int64

In [ ]:
df['col1'] > 2   #  Apply condition on single column

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [ ]:
df['col2'] == 444 #  Apply condition on single column

0     True
1    False
2    False
3     True
Name: col2, dtype: bool

In [ ]:
df[(df['col1'] > 2)   & (df['col2'] == 444)] #  Apply condition on two columns with AND

col1  col2 col3
3     4   444  xyz

In [ ]:
df[(df['col1'] > 2)   | (df['col2'] == 444)]     #  Apply condition on two columns with OR

col1  col2 col3
0     1   444  abc
2     3   666  ghi
3     4   444  xyz

### Applying Functions

In [ ]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
def test(x):
  return x**2

In [ ]:
df['col1'].apply(test) # apply is in-build function , which helps to call any external functon on dataframe

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [ ]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

**Permanently Removing a Column**

In [ ]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
del df['col1']

In [ ]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

**Get column and index names:**

In [ ]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
df.sort_values(by='col2') # sort data based on col2 in asc order

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [ ]:
df.sort_values(by='col2',ascending=False) # sort data based on col2 in desc order

col2 col3
2   666  ghi
1   555  def
0   444  abc
3   444  xyz

In [ ]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

**Find Null Values or Check for Null Values**

In [ ]:
data = {'col1':[1,2,3,4],'col2':[444,555,666,np.nan],'col3':['abc',np.nan,'ghi','xyz']}
df1 = pd.DataFrame(data)

In [ ]:
df1

col1   col2 col3
0     1  444.0  abc
1     2  555.0  NaN
2     3  666.0  ghi
3     4    NaN  xyz

In [ ]:
df1.isnull()

col1   col2   col3
0  False  False  False
1  False  False   True
2  False  False  False
3  False   True  False

# Merging, Joining, and Concatenating

There are 3 main ways of combining DataFrames together: Merging, Joining and Concatenating. In this lecture we will discuss these 3 methods with examples.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_jan = {'cust_id1':[1,2,3],'jan_amount':[20,22,35]}
data_feb = {'cust_id2':[1,2,4],'feb_amount':[30,32,45]}

In [ ]:
df_jan = pd.DataFrame(data_jan)
df_feb = pd.DataFrame(data_feb)

In [ ]:
df_jan

cust_id1  jan_amount
0         1          20
1         2          22
2         3          35

In [ ]:
df_feb

cust_id2  feb_amount
0         1          30
1         2          32
2         4          45

In [ ]:
pd.merge(df_jan, df_feb,how='inner',left_on='cust_id1', right_on='cust_id2') # get only common records (1,2) based on common column(cust_id) values

cust_id1  jan_amount  cust_id2  feb_amount
0         1          20         1          30
1         2          22         2          32

In [ ]:
pd.merge(df_jan, df_feb,how='left')  # get common + extra rec from LHS dataframe

cust_id  jan_amount  feb_amount
0        1          20        30.0
1        2          22        32.0
2        3          35         NaN

In [ ]:
pd.merge(df_jan, df_feb,how='right')  # get common + extra rec from RHS dataframe

cust_id  jan_amount  feb_amount
0        1        20.0          30
1        2        22.0          32
2        4         NaN          45

In [ ]:
x = pd.merge(df_jan, df_feb,how='outer',left_on='cust_id1', right_on='cust_id2')  # get common + extra rec from both dataframes

In [ ]:
x

cust_id1  jan_amount  cust_id2  feb_amount
0       1.0        20.0       1.0        30.0
1       2.0        22.0       2.0        32.0
2       3.0        35.0       NaN         NaN
3       NaN         NaN       4.0        45.0

## Concatenation

Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use **pd.concat** and pass in a list of DataFrames to concatenate together:

In [ ]:
data1 = {'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3'],'C': ['C0', 'C1', 'C2', 'C3']}
df1 = pd.DataFrame(data1)
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [ ]:
data2 = {'A': ['A4', 'A5', 'A6', 'A7'],'B': ['B4', 'B5', 'B6', 'B7'],'C': ['C4', 'C5', 'C6', 'C7'],'D': ['D4', 'D5', 'D6', 'D7']}
df2 = pd.DataFrame(data2,index=[4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df2,df1])

A   B   C    D
4  A4  B4  C4   D4
5  A5  B5  C5   D5
6  A6  B6  C6   D6
7  A7  B7  C7   D7
0  A0  B0  C0  NaN
1  A1  B1  C1  NaN
2  A2  B2  C2  NaN
3  A3  B3  C3  NaN

## Joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

df2 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
df1

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [ ]:
df2

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [ ]:
df1.join(df2,how='left')

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

Python project link : https://drive.google.com/file/d/1ubJ_24IbVcj85XJU_OPZaSXF9FXqrEgN/view?usp=sharing

File Handling in Dataframe

Upload data file from your localhost to colab

In [ ]:
from google.colab import files
data = files.upload()

Saving customers.xml to customers.xml
Saving products.xml to products.xml
Saving transactions.xml to transactions.xml


In [ ]:
ls

customers.csv   products.csv   sample_data/       transactions.xml
customers.json  products.json  transactions.csv
customers.xml   products.xml   transactions.json


In [ ]:
df_cutomers_csv = pd.read_csv('customers.csv')

In [ ]:
df_cutomers_csv.head()

'custno' 'firstname' 'lastname' 'gender'  'age' 'profession'  'contactNo'  \
0         1      Leslie       Bass        F     27            B        37307   
1         2        Judy      Burks        M     53            S        84759   
2         3      Marsha      Doyle        F     48            B        80932   
3         4      Alexis     Battle        M     27            S        71701   
4         5      Martha      Combs        F     49            B        83947   

                'emailId'   'city'    'state' 'isActive'        'createdDate'  \
0  endslost@everyma1l.org   Gibson   Dellwood          Y  2017-09-21 12:38:22   
1  rfleming@hotma1l.co.uk  Suwanee     Trabue          Y  2017-05-22 05:29:22   
2    arethe53@ma1lbox.net    Perry  Moxadarla          Y  2017-09-03 12:11:29   
3      ofcame@ma1lbox.org   Morven     Dennis          Y  2017-02-16 04:05:35   
4   camedied@everyma1l.us   Ocilla  Greenwood          Y  2017-05-15 07:34:35   

         'UpdatedDate'  
0  2017-10-18 12:12:28  
1  2017-10-18 12:12:28  
2  2017-10-18 12:12:28  
3  2017-10-18 12:12:28  
4  2017-10-18 12:12:28

In [ ]:
df_cutomers_csv["'custno'"].head()

0    1
1    2
2    3
3    4
4    5
Name: 'custno', dtype: int64

In [ ]:
pd.read_csv

In [ ]:
# customers_data dataframe contains customers records, which we have in customers.csv file
# transactions_data dataframe contains transactions records, which we have in transactions.csv file
# products_data dataframe contains products records, which we have in products.csv file

In [ ]:
Customer_Final = pd.merge(left=pd.merge(left=customers_data,right=transactions_data,
                                        how='left',left_on= "'custno'",right_on="'custno'"),
                          right=products_data,how='inner',left_on="'productno'",right_on="'productno'")